using System.Windows;using System.Windows.Controls;using System.Windows.Media;
namespace NetControl.Windows;
public partial class MainWindow:Window
{
 RouterOsApi api=new(); Dictionary<string,Button> nav=new(); public MainWindow(){InitializeComponent();ShowDashboard();}
 void Nav_Click(object s,RoutedEventArgs e){var id=(s as Button)?.Tag?.ToString();switch(id){case"dashboard":ShowDashboard();break;case"devices":ShowDevices();break;case"hotspot":ShowCommand("Hotspot","/ip/hotspot/print");break;case"cards":ShowCards();break;case"sales":ShowText("المبيعات","إدارة المبيعات والموزعين والكروت.");break;case"programming":ShowCommand("برمجة المايكروتيك","/system/resource/print");break;case"console":ShowConsole();break;case"backup":ShowText("النسخ الاحتياطي","إنشاء وإدارة نسخ إعدادات MikroTik.");break;case"account":ShowText("الحساب والاشتراك","الحساب والخطة الحالية ومزايا PRO/VIP.");break;}}
 void ShowDashboard(){PageTitle.Text="لوحة التحكم";var p=new StackPanel();p.Children.Add(T("NetControl Windows","28"));p.Children.Add(T("نسخة Windows أصلية تعتمد على RouterOS API المباشر.","16"));p.Children.Add(T("الحالة: "+(api.Connected?"متصل":"غير متصل"),"18"));PageContent.Content=p;}
 void ShowDevices(){PageTitle.Text="الأجهزة والراوترات";var p=new StackPanel();foreach(var x in new[]{"إضافة جهاز","IP / DNS","Port 8728 / 8729","اسم المستخدم","كلمة المرور"})p.Children.Add(new TextBox{Text=x});p.Children.Add(new Button{Content="اتصال بالراوتر",Tag="connect",Padding=new Thickness(18)});PageContent.Content=p;}
 void ShowCommand(string title,string command){PageTitle.Text=title;var p=new StackPanel();p.Children.Add(T("الأمر: "+command,"16"));var b=new Button{Content="تنفيذ وتحديث البيانات"};b.Click+=async(_,__)=>{try{var rows=await api.CommandAsync(command);p.Children.Add(T(string.Join("\n",rows.SelectMany(r=>r.Select(k=>$"{k.Key}={k.Value}"))),"13"));}catch(Exception ex){p.Children.Add(T("خطأ: "+ex.Message,"14"));}};p.Children.Add(b);PageContent.Content=p;}
 void ShowCards(){ShowText("الكروت المطبوعة","واجهة إدارة الكروت والقوالب والطباعة PDF محفوظة ضمن Assets. سيتم ربط محرر القوالب ووظائف الإنشاء بالمرحلة التالية.");}
 void ShowConsole(){PageTitle.Text="Console";var p=new StackPanel();var cmd=new TextBox{Height=80,AcceptsReturn=true};p.Children.Add(cmd);var outp=new TextBox{IsReadOnly=true,Height=400,TextWrapping=TextWrapping.Wrap};p.Children.Add(new Button{Content="تنفيذ",Command=null});p.Children.Add(outp);PageContent.Content=p;}
 void ShowText(string title,string text){PageTitle.Text=title;PageContent.Content=new Border{Padding=new Thickness(30),Child=T(text,"18")};}
 TextBlock T(string s,string size)=>new(){Text=s,FontSize=double.Parse(size),Margin=new Thickness(8)};
 async void Connect_Click(object s,RoutedEventArgs e){var w=new Window{Title="اتصال MikroTik",Width=430,Height=330,FlowDirection=FlowDirection.RightToLeft};var p=new StackPanel{Margin=new Thickness(20)};var h=new TextBox{Text="127.0.0.1"};var port=new TextBox{Text="8728"};var u=new TextBox{Text="admin"};var pass=new PasswordBox();var b=new Button{Content="اتصال",Margin=new Thickness(5)};p.Children.Add(new TextBlock{Text="IP / DNS"});p.Children.Add(h);p.Children.Add(new TextBlock{Text="Port"});p.Children.Add(port);p.Children.Add(new TextBlock{Text="Username"});p.Children.Add(u);p.Children.Add(new TextBlock{Text="Password"});p.Children.Add(pass);p.Children.Add(b);w.Content=p;b.Click+=async(_,__)=>{try{await api.ConnectAsync(h.Text,int.Parse(port.Text),u.Text,pass.Password);w.Close();ShowDashboard();}catch(Exception ex){MessageBox.Show(ex.Message,"NetControl");}};w.ShowDialog();}
}
